image: python:3

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Management.gitlab-ci.yml

variables:
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache

stages:
  - test
  - deploy

.tests:
  stage: test
  cache:
    key: $CI_JOB_NAME
    paths:
      - .cache/
  script:
    - python -V
    - python -m pip install -U pip
    - pip install -r requirements.txt
    - pytest

test:3.5:
  image: python:3.5
  extends: .tests

test:3.6:
  image: python:3.6
  extends: .tests

test:3.7:
  image: python:3.7
  extends: .tests

test:3.8:
  image: python:3.8
  extends: .tests

deploy:
  stage: deploy
  cache:
    key: deploy
    paths:
      - .cache/
  script:
    - python -V
    - pip install twine wheel
    - python setup.py sdist bdist_wheel
    - twine upload dist/*
  only:
    - tags
