image: python:3.7

variables:
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache

cache:
  key: $CI_JOB_NAME
  paths:
    - .cache/

before_script:
  - python -V

stages:
  - test
  - deploy

test:3.5:
  image: python:3.5
  stage: test
  script:
    - pip install -r requirements/requirements-gitlab-ci.txt
    - tox -e py35

test:3.6:
  image: python:3.6
  stage: test
  script:
    - pip install -r requirements/requirements-gitlab-ci.txt
    - tox -e py36

test:3.7:
  stage: test
  script:
    - pip install -r requirements/requirements-gitlab-ci.txt
    - tox -e py37

deploy:
  stage: deploy
  script:
    - pip install -r requirements/requirements-packaging.txt
    - python setup.py sdist bdist_wheel
    - twine upload dist/*
  only:
    - tags
    - triggers
    - schedules
